# permissions for end users to view bcfks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bcfks-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bcfks-operator
    app.kubernetes.io/part-of: bcfks-operator
    app.kubernetes.io/managed-by: kustomize
  name: bcfks-viewer-role
rules:
- apiGroups:
  - bcfks.io
  resources:
  - bcfks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bcfks.io
  resources:
  - bcfks/status
  verbs:
  - get
